//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string State { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total_cost { get; set; }
        public string Type { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Role Role { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
