//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public byte[] Date { get; set; }
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Role Role { get; set; }
    }
}
